const data = {
  products: [
    {
      name: 'Pan Árabe',
      slug: 'pan-arabe',
      category: 'Shirts',
      image: '/images/Pan Árabe - Samarit Hanna.png',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Jocoque Seco',
      slug: 'jocoque-seco',
      category: 'Shirts',
      image: '/images/Jocoque Seco - Samarit Hanna.png',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    // {
    //   name: 'Nike Slim Pant',
    //   slug: 'nike-slim-pant',
    //   category: 'Pants',
    //   image: '/images/p3.jpg',
    //   price: 25,
    //   countInStock: 15,
    //   brand: 'Nike',
    //   rating: 4.5,
    //   numReviews: 14,
    //   description: 'high quality product',
    // },
    // {
    //   name: 'Adidas Fit Pant',
    //   slug: 'adidas-fit-pant',
    //   category: 'Pants',
    //   image: '/images/p4.jpg',
    //   price: 65,
    //   countInStock: 5,
    //   brand: 'Puma',
    //   rating: 4.5,
    //   numReviews: 10,
    //   description: 'high quality product',
    // },
  ],
};
export default data;
